{{- if and .Values.serviceAccount.create .Values.role.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ ternary "Cluster" "" .Values.role.cluster }}RoleBinding
metadata:
  name: {{ include "provisioner.roleBindingName" . }}
  labels:
    {{- include "provisioner.labels" . | nindent 4 }}
  {{- with .Values.role.bindingAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
subjects:
- kind: ServiceAccount
  name: {{ include "provisioner.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: {{ ternary "Cluster" "" .Values.role.cluster }}Role
  name: {{ include "provisioner.roleName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
