{{- if .Values.role.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ ternary "Cluster" "" .Values.role.cluster }}Role
metadata:
  name: {{ include "provisioner.roleName" . }}
  labels:
    {{- include "provisioner.labels" . | nindent 4 }}
  {{- with .Values.role.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create"]
{{- end }}
