{{- if and .Values.serviceAccount.create .Values.clusterRole.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "releaser.clusterRoleBindingName" . }}
  labels:
    {{- include "releaser.labels" . | nindent 4 }}
  {{- with .Values.clusterRole.bindingAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
subjects:
- kind: ServiceAccount
  name: {{ include "releaser.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "releaser.clusterRoleName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
