apiVersion: v1
kind: Pod
metadata:
  name: pod-with-dynamic-reclaimable-pvc
spec:
  volumes:
    - name: reclaimable-pvc
      ephemeral:
        volumeClaimTemplate:
          spec:
            storageClassName: reclaimable-storage-class
            resources:
              requests:
                storage: 1Gi
            accessModes:
              - ReadWriteOnce
  containers:
    - name: web
      image: nginx
      volumeMounts:
        - name: reclaimable-pvc
          mountPath: /data