kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: reclaimable-storage-class
  annotations:
    reclaimable-pv-releaser.kubernetes.io/controller-id: dynamic-reclaimable-pvc-controllers
provisioner: rancher.io/local-path
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer